### PR TITLE
Fix the drain script and post-start

### PR DESCRIPTION
**Pull request by lubronzhan**
https://www.pivotaltracker.com/story/show/173664119
post-start doesn't run because it's missing `main`
drain script didn't fail on error because it was missing `$ErrorActionPreference = "Stop";`
Also added new try/catch logic to make retry actually work

https://pks.ci.cf-app.com/teams/dev/pipelines/pks-api-fix_drain

### CODE REVIEW

**Comment by daniel-keeney** [comment]
@lubronzhan which pipelines was this tested with?

**Comment by lubronzhan** [comment]
@daniel-keeney Sorry I didn't use pipeline, but I built dev tile with it and test manually myself with the testing team.
How did you create dev release for this for pipelines?
Do you use this one? https://pks.ci.cf-app.com/teams/bosh-lifecycle/pipelines/cfcr-dependencies-1.9.x/jobs/create-kubo-release-windows/builds/10

**Comment by daniel-keeney** [comment]
@lubronzhan you can fly a dev version of that pipeline based on a feature branch.  Edit `kubo-odb-ci/configs/1.9.x/variables.yml` to point to the branch you want, then set it up with `set_pks_pipeline.sh 1.9.x --dev --team bosh-lifecycle-dev --suffix my-feature -p cfcr-dependencies`

The resulting pipeline will give you the lines to paste into `p-pks-integrations/dependencies.yml` to use the final release from the feature branch that you want.

**Comment by lubronzhan** [comment]
Thanks @daniel-keeney , I ran it here https://pks.ci.cf-app.com/teams/dev/pipelines/pks-api-fix_drain

**Pull request closed without merging**
